### ISSUE TITLE
llkp.filter

### ISSUE THREAD

**Issue by puckkagames** [whtahy/LLKP#1]
Missing file llkp.filter

**Comment by whtahy** [comment]
Hi there!  Thanks for the issue.  Unfortunately, the filter is still a few years out of date haha, not sure when I'll have it fully updated for patch 3.23.

Are you looking for anything in particular?  I can maybe prioritize that.

**Comment by whtahy** [comment]
Filter is fully updated for 3.24, although it now requires a rust build step to pull prices from poe.ninja and for some find/replace styling.
